version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: t3kit/ubuntu16-php7-apache:0.0.1
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');" && \
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');"
      - run:
          name: Install Project Dependencies
          command: php composer.phar install
      - run:
          name: Install t3kit database
          command: |
            docker exec -it web /t3kit_db/setupdb.sh
      #- run:
      #    name: Install Project Dependencies
      #    command: cd /var/www && sh /docker_conf/run.sh